SUBUTAI-1115: implement lock mechanism for concurent operation on same lxc

diff --git a/cli-dev/src/main/bindings/master_create b/cli-dev/src/main/bindings/master_create
--- a/cli-dev/src/main/bindings/master_create
+++ b/cli-dev/src/main/bindings/master_create
@@ -2,6 +2,15 @@
 
 
 function master_create {
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
+  lock_subutai_system
+  if [ $? != 0 ]; then echo "System cannot be locked!"; exit 1; fi
+
   # Check for Master Existence
   # ---------------------------------------------------------------------------
 
@@ -92,6 +101,9 @@ function master_create {
   addmount master opt lxc
   addmount master home lxc-data
   addmount master var lxc-data
+  
+  unlock_subutai_system
+  if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
 }
 
 function master_create_description {
diff --git a/cli-dev/src/main/bindings/master_destroy b/cli-dev/src/main/bindings/master_destroy
--- a/cli-dev/src/main/bindings/master_destroy
+++ b/cli-dev/src/main/bindings/master_destroy
@@ -7,9 +7,18 @@ function master_destroy {
     exit 1
   fi
 
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
   local container="master"
   local package_name=`get_package_name $container`
   local debian_root="$SUBUTAI_TMPDIR/$container"
+  
+  lock_subutai_system
+  if [ $? != 0 ]; then echo "System cannot be locked!"; exit 1; fi
   
   # Confirm destroy operation
   echo WARNING: this destroys everything mercilessly
@@ -17,7 +26,9 @@ function master_destroy {
     read -p "Do you wish to destroy master template? [Y/N]" yn
     case $yn in
       [Yy]* ) break;;
-      [Nn]* ) exit 1;;
+      [Nn]* )unlock_subutai_system
+             if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi 
+             exit 1;;
       * ) echo "Please answer yes or no.";;
     esac
   done
@@ -51,6 +62,8 @@ function master_destroy {
   
   # Remove relevant directories under $SUBUTAI_TMPDIR if any
   rm -rf $debian_root
+  container_unlock_common $container
+  if [ $? != 0 ]; then echo "Master cannot be unlocked!"; exit 1; fi
 }
 
 
diff --git a/cli-dev/src/main/bindings/master_export b/cli-dev/src/main/bindings/master_export
--- a/cli-dev/src/main/bindings/master_export
+++ b/cli-dev/src/main/bindings/master_export
@@ -19,6 +19,15 @@ function usage {
 
 function master_export {
 
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
+  lock_subutai_system
+  if [ $? != 0 ]; then echo "System cannot be locked!"; exit 1; fi
+
   # ---------------------------------------------------------------------------
   # (1) perform some sanity checks
   # ---------------------------------------------------------------------------
@@ -30,6 +39,8 @@ function master_export {
   if [ -f "$debian_file" ]; then
     msg_error "It seems the debian package file has already been generated"
     msg_error "Run rm -rf $debian_root* and try again"
+    unlock_subutai_system
+    if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -83,6 +94,8 @@ function master_export {
   pkg=`deb_pkg $container`
   # Remove debian root directory after debian package generation
   rm -rf $debian_root
+  unlock_subutai_system
+  if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
 
 }
 
diff --git a/cli-dev/src/main/bindings/master_import b/cli-dev/src/main/bindings/master_import
--- a/cli-dev/src/main/bindings/master_import
+++ b/cli-dev/src/main/bindings/master_import
@@ -19,6 +19,15 @@ function master_import {
   
   msg_info "APT_GET_INVOCATION: $APT_GET_INVOCATION"
   if [ -z "$APT_GET_INVOCATION" -o "$APT_GET_INVOCATION" != "true" ]; then
+    if [ "`is_system_locked`" == "true" ]
+    then
+       echo "System locked by a subutai process"
+       exit 1
+    fi
+
+    lock_subutai_system
+    if [ $? != 0 ]; then echo "System cannot be locked!"; exit 1; fi
+
     msg_info "subutai master_import called from command line"
     local debian_package_name=`get_debian_package_name $container`
     local debian_file="$SUBUTAI_TMPDIR/$debian_package_name.deb"
@@ -26,6 +35,8 @@ function master_import {
 
     if [ ! -f "$debian_file" ]; then
       msg_error "Could not find template file \"$debian_file\". Aborting ..."
+      unlock_subutai_system
+      if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
       exit 1
     fi
 
@@ -33,24 +44,29 @@ function master_import {
     is_package_installed $package_name
     if [ $? = 0  ]; then
       msg_error "Template $container seems already installed, please destroy first"
+      unlock_subutai_system
+      if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
       exit 1
     fi
 
     dpkg -i $debian_file
     if [ $? -eq 0 ]; then
       msg_ok "Debian package of $package_name is installed succesfully"
+      unlock_subutai_system
+      if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
       exit 0
     else
       msg_error "Debian package of $package_name could not be installed, removing"
       subutai master_destroy
       apt-get --assume-yes --force-yes purge $package_name
+      unlock_subutai_system
+      if [ $? != 0 ]; then echo "System cannot be unlocked!"; exit 1; fi
       exit 1
     fi
     popd
   else
     msg_info "subutai master_import called while installing master from the debian package"
   fi
-
 
   lxc_home=/var/lib/lxc/master
   lxc_rootfs=$lxc_home/rootfs
diff --git a/cli/src/main/bindings/clone b/cli/src/main/bindings/clone
--- a/cli/src/main/bindings/clone
+++ b/cli/src/main/bindings/clone
@@ -13,8 +13,20 @@ function clone_usage {
 
 
 function clone {
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
   local parent="$1"
   local child="$2"
+  
+  if [ "`are_containers_locked_clone $parent $child`" == "true" ]
+  then
+     echo "Container(s) locked by a subutai process"
+     exit 1
+  fi
 
   if [ -z "$parent" ]; then
     msg_error "Parameters not provided. Aborting ..."
@@ -25,12 +37,17 @@ function clone {
     msg_error "Child parameter not provided. Aborting ..."
     show_usage "`usage`"
   fi
+  
+  lock_container_write $parent $child
+  if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
 
   # NOTE: underscore for our own lxc clone impl not supplied lxc-clone
   lxc_clone $parent $child "`usage`"
   git_child_branch $child
 
   msg_ok "Successfully cloned $child container from $parent"
+  unlock_container_write $child
+  if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
 }
 
 
diff --git a/cli/src/main/bindings/demote b/cli/src/main/bindings/demote
--- a/cli/src/main/bindings/demote
+++ b/cli/src/main/bindings/demote
@@ -12,17 +12,36 @@ function demote_usage {
 
 
 function demote {
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
   local temp="$1"
+
+  if [ "`are_containers_locked_read $temp`" == "true" ]
+  then
+     echo "Container(s) locked by a subutai process"
+     exit 1
+  fi
+
+  lock_container_read $temp
+  if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
 
   #check for master	
   if [ $temp == "master" ]; then
     msg_error "Master templated cannot be demoted. Aborting ..."
+    unlock_container_read $temp
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
   # check to make sure we have a template name - usage if not
   if [ -z "$temp" ]; then
     msg_error "Template argument not provided. Aborting ..."
+    unlock_container_read $temp
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     show_usage "`demote_usage`"
   fi
 
@@ -30,6 +49,8 @@ function demote {
   lxc_assert "$temp"
   if [ "false" == "`zfs_is_template $temp`" ]; then
     msg_error "Supplied template name \"$temp\" is not a template. Aborting ..."
+    unlock_container_read $temp
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -37,9 +58,13 @@ function demote {
   local child_count="$?"
   if [ "$child_count" -gt 0 ]; then
     msg_error "Template \"$temp\" cannot be demoted with $child_count children."
+    unlock_container_read $temp
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   elif [ "true" == "`is_registered $temp`" ]; then
     msg_error "Cannot demote registered template \"$temp\""
+    unlock_container_read $temp
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   else
     msg_info "Demoting template \"$temp\" with no children."
@@ -75,6 +100,8 @@ function demote {
   zfs set readonly=off "lxc/$temp"
 
   msg_ok "Successfully demoted $temp"
+  unlock_container_read $temp
+  if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
 }
 
 
diff --git a/cli/src/main/bindings/destroy b/cli/src/main/bindings/destroy
--- a/cli/src/main/bindings/destroy
+++ b/cli/src/main/bindings/destroy
@@ -49,8 +49,19 @@ function destroy {
 
   local clone="$1"
 
+  if [ "`are_containers_locked_read $clone`" == "true" ]
+  then
+     echo "Container locked by a subutai process"
+     exit 1
+  fi
+  
+  lock_container_read $clone
+  if [ $? != 0 ]; then echo "Container cannot be locked!"; exit 1; fi
+
   if [ "$clone" == "master" ]; then
     msg_error "Use subutai master_destroy instead of subutai destroy"
+    unlock_container_read $clone
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -70,6 +81,8 @@ function destroy {
   if [ $child_count -gt 0 ]; then
     if [ $recursive == "false" ]; then
       msg_error "Cannot destroy \"$clone\", it has $child_count child containers."
+      unlock_container_read $clone
+      if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
       exit 1
     elif [ $recursive == "true" -a $force == "false" ]; then
       # Confirm recursive destroy operation
@@ -78,7 +91,9 @@ function destroy {
         read -p "Do you wish to destroy $clone template? [Y/N]" yn
         case $yn in
           [Yy]* ) break;;
-          [Nn]* ) exit 1;;
+          [Nn]* )unlock_container_read $clone
+                 if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi 
+                 exit 1;;
           * ) echo "Please answer yes or no.";;
         esac
       done
@@ -99,6 +114,8 @@ function destroy {
   if [ "`is_dpkg_locked`" == "true" ]
   then
     echo "$1 import FAILED! dpkg is locked by process!"
+    unlock_container_read $clone
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
  
@@ -132,6 +149,8 @@ function destroy {
   # (8) remove relevant directories under $SUBUTAI_TMPDIR if any
   local debian_root="$SUBUTAI_TMPDIR/$container"
   rm -rf $debian_root
+  unlock_container_read $clone
+  if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
   exit 0
 }
 
diff --git a/cli/src/main/bindings/import b/cli/src/main/bindings/import
--- a/cli/src/main/bindings/import
+++ b/cli/src/main/bindings/import
@@ -24,6 +24,12 @@ function import_usage {
 # (5) Mount the rootfs filesystem on /var/lib/lxc/$template/rootfs
 
 function import {
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
   local container="$1"
   local debian_package_name=`get_debian_package_name $container`
   local debian_file="$SUBUTAI_TMPDIR/$debian_package_name.deb"
@@ -85,30 +91,58 @@ function import {
 
     if [ "$is_local" == "true" ]
     then
+      if [ "`are_containers_locked_read $container`" == "true" ]
+      then
+         echo "Container(s) locked by a subutai process"
+         exit 1
+      fi
+     
+      lock_container_read $container
+      if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
+
       dpkg -i $debian_file
       if [ $? -eq 0 ]; then
         msg_info "Debian package of $package_name is installed succesfully from local"
+        unlock_container_read $container
+        if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
         exit 0
       else
         msg_error "Debian package of $package_name could not be installed, removing"
         subutai destroy $container
         apt-get --assume-yes --force-yes purge $package_name
+        unlock_container_read $container
+        if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
 	exit 1
       fi
     elif [ "`is_registered $container`" == "true" ]
     then
+      if [ "`are_containers_locked_read $container`" == "true" ]
+      then
+         echo "Container(s) locked by a subutai process"
+         exit 1
+      fi
+
+      lock_container_read $container
+      if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
+
       apt-get --assume-yes --force-yes install $package_name
       if [ $? -eq 0 ]; then
        msg_info "Debian package of $package_name is installed succesfully from repo"
+       unlock_container_read $container
+       if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
        exit 0
       else
         msg_error "Debian package of $package_name could not be installed, removing"
         subutai destroy $container
         apt-get --assume-yes --force-yes purge $package_name
+        unlock_container_read $container
+        if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
         exit 1
       fi
     else
       msg_error "Package $package_name is not found!"
+      unlock_container_read $container
+      if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
       exit 1
     fi
   else
@@ -125,6 +159,8 @@ function import {
   if [ "`zfs_is_template $parent`" == "false" ]; then
     msg_error "Parent \"$parent\" is NOT a template. Aborting ..."
     apt-get --assume-yes --force-yes purge $package_name
+    unlock_container_read $container
+    if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
     exit 1
   else
     msg_info "    - check passed: parent \"$parent\" is a template"
@@ -134,6 +170,8 @@ function import {
   if [ "`is_registered $parent`" == "false" ]; then
     msg_error "Parent \"$parent\" is NOT registered. Aborting ..."
     apt-get --assume-yes --force-yes purge $package_name
+    unlock_container_read $container
+    if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
     exit 1
   else
     msg_info "    - check passed: parent \"$parent\" is registered"
@@ -157,7 +195,6 @@ function import {
   zfs recv lxc/$container-opt < $deltas/opt.delta
   zfs recv lxc-data/$container-var < $deltas/var.delta
   zfs recv lxc-data/$container-home < $deltas/home.delta
-
 }
 
 
diff --git a/cli/src/main/bindings/promote b/cli/src/main/bindings/promote
--- a/cli/src/main/bindings/promote
+++ b/cli/src/main/bindings/promote
@@ -23,6 +23,12 @@ function promote_usage {
 # (4) shutdown & '@template' snapshot all mounts, and apply "keep" holds
 
 function promote {
+  if [ "`is_system_locked`" == "true" ]
+  then
+     echo "System locked by a subutai process"
+     exit 1
+  fi
+
   OPTIND=0
   if [ "$1" == "promote" ]; then
     shift
@@ -73,9 +79,20 @@ function promote {
  
   local lxc="$1"
 
+  if [ "`are_containers_locked_read $lxc`" == "true" ]
+  then
+     echo "Container(s) locked by a subutai process"
+     exit 1
+  fi
+
+  lock_container_read $lxc
+  if [ $? != 0 ]; then echo "Containers cannot be locked!"; exit 1; fi
+
   # The master is already a template
   if [ "$lxc" == "master" ]; then
     msg_error "The master is already a template. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -87,6 +104,8 @@ function promote {
   # check to make sure the container is NOT already a template
   if [ "`zfs_is_template $lxc`" == "true" ]; then
     msg_error "Container \"$lxc\" is already a template. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   else
     msg_info "    - check passed: \"$lxc\" is NOT a template"
@@ -95,6 +114,8 @@ function promote {
   # check to make sure container is NOT registered as a template
   if [ "`is_registered $lxc`" == "true" ]; then
     msg_error "A template with name \"$lxc\" is registered. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   else
     msg_info "    - check passed: \"$lxc\" is NOT registered"
@@ -105,6 +126,8 @@ function promote {
   # check to make sure the parent is a template
   if [ "`zfs_is_template $parent`" == "false" ]; then
     msg_error "Parent \"$parent\" is NOT a template. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   else
     msg_info "    - check passed: parent \"$parent\" is a template"
@@ -189,6 +212,8 @@ function promote {
   zfs set readonly=on lxc-data/$lxc_template-home
 
   msg_ok "Successfully promoted $lxc_template"
+  unlock_container_read $lxc
+  if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
 }
 
 
diff --git a/cli/src/main/lib/lxc_ops b/cli/src/main/lib/lxc_ops
--- a/cli/src/main/lib/lxc_ops
+++ b/cli/src/main/lib/lxc_ops
@@ -9,6 +9,8 @@ function lxc_assert_name {
   local lxc="$1"
   if [ -n "`echo $lxc | grep '-'`" ]; then
     msg_error "Arg \"$lxc\" contains illegal dash character."
+    unlock_container_read $1
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 }
@@ -69,11 +71,15 @@ function lxc_assert_no {
 
   if [ -z "$lxc" ]; then
     msg_error "No value provided for container's name. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     show_usage "$usage"
   fi
   lxc-info -n $lxc > /dev/null 2>&1
   if [ $? == 0 ]; then
     msg_error "Container \"$lxc\" exists. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     show_usage "$usage"
   else
     msg_info "    - check passed: container \"$lxc\" does NOT exist."
@@ -87,12 +93,16 @@ function lxc_assert {
 
   if [ -z "$lxc" ]; then
     msg_error "No value provided for container's name. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     show_usage "$usage"
   fi
 
   lxc-info -n $lxc > /dev/null 2>&1
   if [ $? != 0 ]; then
     msg_error "Container \"$lxc\" does NOT exist. Aborting ..."
+    unlock_container_read $lxc
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     show_usage "$usage"
   else
     msg_info "    - check passed: container \"$lxc\" exists."
@@ -179,11 +189,15 @@ function lxc_clone {
 
   if [ -z "$parent" ]; then
     msg_error "Parameters not provided. Aborting ..."
+    unlock_container_read $child
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
   if [ -z "$child" ]; then
     msg_error "Child parameter not provided. Aborting ..."
+    unlock_container_read $parent
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -200,6 +214,8 @@ function lxc_clone {
 
   if [ "`zfs_is_template $parent`" == "false" ]; then
     msg_error "Parent \"$parent\" is not a template"
+    unlock_container_read $child
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   else
     msg_info "    - parent \"$parent\" is a template"
@@ -258,11 +274,15 @@ function lxc_copy {
 
   if [ -z "$parent" ]; then
     msg_error "Parameters not provided. Aborting ..."
+    unlock_container_read $child
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
   if [ -z "$child" ]; then
     msg_error "Child parameter not provided. Aborting ..."
+    unlock_container_read $parent
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -279,6 +299,8 @@ function lxc_copy {
 
   if [ "`zfs_is_template $parent`" == "true" ]; then
     msg_error "Parent \"$parent\" must not be a template for a copy op"
+    unlock_container_read $child
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   else
     msg_info "    - parent \"$parent\" is not a template"
@@ -322,11 +344,15 @@ function lxc_rename {
 
   if [ -z "$src" ]; then
     msg_error "Parameters not provided for source container. Aborting ..."
+    unlock_container_read $dst
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
   if [ -z "$dst" ]; then
     msg_error "Parameters not provided for destination container. Aborting ..."
+    unlock_container_read $src
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -343,6 +369,8 @@ function lxc_rename {
 
   if [ "`zfs_is_template $src`" == "true" ]; then
     msg_error "Source \"$src\" must not be a template for a rename op"
+    unlock_container_read $dst
+    if [ $? != 0 ]; then echo "Container(s) cannot be unlocked!"; exit 1; fi
     exit 1
   fi
 
@@ -385,5 +413,4 @@ function lxc_rename {
   git_rename_branch "$src" "$dst"
   lxc_stop "$dst"
 }
-
 
