update of debian creator scripts.

diff --git a/big-data/pack-funcs b/big-data/pack-funcs
--- a/big-data/pack-funcs
+++ b/big-data/pack-funcs
@@ -46,6 +46,66 @@ getSourcesToRelevantDirectories() {
 }
 
 
+checkPackageVersion() {
+
+  CONTROL="/var/lib/jenkins/jobs/master.get_branch_repo/workspace/big-data/$productName/$productName/DEBIAN/control"
+  TARGET="/var/lib/jenkins/Automation/Bigdata/$productName"
+
+  lineNumberVersion=$(sed -n '/Version:/=' $CONTROL)
+  lineVersion=$(sed $lineNumberVersion!d $CONTROL)
+  version_new=$(echo $lineVersion | awk -F":" '{split($2,a," ");print a[1]}')
+  versionFirst_new=$(echo $version_new | awk -F"." '{print $1}')
+  versionSecond_new=$(echo $version_new | awk -F"." '{print $2}')
+
+  version_tmp=$(echo $version_new | awk -F"." '{print $3}')
+  versionThird_new=$(echo $version_tmp | awk -F"-" '{print $1}')
+  patch_new=$(echo $version_tmp | awk -F"-" '{print $2}')
+
+
+  deb_name=`ls -lt $TARGET | awk '{ print $9 }' | grep .deb | head -1`
+  version_prev=$(echo $deb_name | awk -F"_" '{print $2}')
+  versionFirst_prev=$(echo $version_prev | awk -F"." '{print $1}')
+  versionSecond_prev=$(echo $version_prev | awk -F"." '{print $2}')
+
+  version_tmp_prev=$(echo $version_new | awk -F"." '{print $3}')
+  versionThird_prev=$(echo $version_tmp_prev | awk -F"-" '{print $1}')
+  patch_prev=$(echo $versiontmp__prev | awk -F"-" '{print $2}')
+
+  if [ "$patch_prev"="" ]; then
+    patch_prev=0
+  fi
+  if [ "$patch_new"="" ]; then
+    patch_new=0
+  fi
+
+  echo "version in control:$version_new current version:$version_prev "
+
+  if [ $versionFirst_new -lt $versionFirst_prev ]; then
+    echo "major: current version is greater than the version in control file. Version in control file:$version_new, current version:$version_prev"
+    exit 0;
+  elif [ $versionFirst_new -eq $versionFirst_prev ]; then
+     if [ $versionSecond_new -lt $versionSecond_prev ]; then
+        echo "minor: current version is greater than the version in control file. Version in control file:$version_new, current version:$version_prev"
+        exit 0;
+     elif [ $versionSecond_new -eq $versionSecond_prev ]; then
+        if [ $versionThird_new -lt $versionThird_prev ]; then
+            echo "micro: current version is greater than the version in control file. Version in control file:$version_new, current version:$version_prev"
+            exit 0;
+        elif [ $versionThird_new -eq $versionThird_prev ]; then 
+          if [ $patch_new -lt $patch_prev  ]; then
+               echo "patch: current version is greater than the version in control file. Version in control file:$version_new, current version:$version_prev"
+           		 exit 0;
+          elif [ $patch_new -eq $patch_prev  ]; then
+               echo "patch: current version is equal to the version in control file. Version in control file:$version_new, current version:$version_prev"
+           		 exit 0;
+          fi
+        fi
+     fi
+  fi
+}
+
+
+
 generateDebianPackage() {
   updatePackageContent $1
   pushd $BASE
@@ -119,4 +179,76 @@ getArchitecture() {
   echo "all"
 }
 
+generateRepoPackage() {
+  #check initial productName is not empty
+  if [[ $1 == "" ]]; then
+    usage
+  fi
+  
+  #Basic path definitions
+  productName=$1
+  productNameUppercase="$(tr '[:lower:]' '[:upper:]' <<< ${productName:0:1})${productName:1}"
+  BASE=/var/lib/jenkins/jobs/master.bigdata.$productName/$productNameUppercase
+  SOURCE="/var/lib/jenkins/jobs/master.get_branch_repo/workspace/big-data/$productName/$productName"
+  TARGET="/var/lib/jenkins/Automation/Bigdata/$productName"
+  PACK="/var/lib/jenkins/Automation/Automation_ISO/mgmt-repo/template-repo-package/"
+  ISOPATH="/var/lib/jenkins/Automation/Automation_ISO/work/custom-iso/pool/extras/"
+ 
+  pushd $BASE
+
+  #get package latest package from ISOPATH to remove it
+  removedPackage=`ls -lt $ISOPATH | grep "subutai-repo-$productName" | awk '{ print $9 }' | grep .deb | head -1`
+  echo "removedPackageName: $removedPackage" 
+   if [ "$removedPackage" != "" ]; then
+      rm $ISOPATH/$removedPackage
+   fi
+
+  #get package full name, for example:subutai-hadoop_1.0.12_all.deb
+  currentPackage=`ls -lt $TARGET | awk '{ print $9 }' | grep .deb | head -1` 
+  echo "CurrentPackageName: $currentPackage"
+  
+  #delete repo package: subutai-repo-hadoop_1.0.12_all.deb
+  if [ -f "$ISOPATH/subutai-repo-$currentPackage" ]; then
+      rm $ISOPATH/subutai-repo-$currentPackage 
+  fi
+
+  #check package starts with subutai tag
+  if [[ "$currentPackage" == "subutai"* ]]; then
+     shortCurrentPackage=`echo "$currentPackage" | awk '{print substr($1,9); }'  | awk '{print substr($0, 0, length($0)-4)}'`
+     echo "shortCurrentPackage: $shortCurrentPackage"
+  fi
+
+  purePackageName=`echo $shortCurrentPackage | awk -F "." '{print $1}' | awk '{print substr($0, 0, length($0)-2)}'`
+  echo "purePackageName: $purePackageName"
+ 
+  #check purePackageName is empty or not
+  if [ -z $purePackageName ] || [ "x$purePackageName" == "x" ]; then
+     echo "Pure package name is empty. Aborting..."
+     exit 1
+  fi
+
+  templateName="temp"
+
+  #check temp folder does exist or not
+  if [ -d "$templateName" ]; then
+    rm -rf "$BASE/$templateName"
+  fi
+    cp -a $PACK $BASE/$templateName
+  
+  sed -i "s/template/subutai-repo-$purePackageName/g" $BASE/$templateName/DEBIAN/control
+  cp $currentPackage $BASE/$templateName/repo/ksks/amd64/trusty/
+  mv $BASE/$templateName/ $BASE/subutai-repo-$shortCurrentPackage
+  
+  CURRENTPACK=$BASE/subutai-repo-$shortCurrentPackage
+  echo "CURRENTPACK: $CURRENTPACK"
+
+  dpkg-deb --build $CURRENTPACK
+  mv $BASE/subutai-repo-"$shortCurrentPackage".deb $ISOPATH
+  rm -rf $BASE/subutai-repo-$shortCurrentPackage
+  rm -rf $BASE/$templateName
+
+  echo "Repo wrapper package Successfully created."
+
+  popd
+}
 
