SUBUTAI-2047: Hive service scripts should return pids of the running processes

diff --git a/big-data/hive/hive/etc/init.d/hive-thrift b/big-data/hive/hive/etc/init.d/hive-thrift
--- a/big-data/hive/hive/etc/init.d/hive-thrift
+++ b/big-data/hive/hive/etc/init.d/hive-thrift
@@ -7,76 +7,75 @@ DESC="Hive Thrift Server"
 CMD_PATT="hive"
 . /lib/lsb/init-functions
 
+
 is_running()
 {
-    if [ -f $PIDFILE ]; then
-        pid=`cat $PIDFILE`
-        grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 0
-        return 1
-    fi
-    return 3
+  if [ -f $PIDFILE ]; then
+    pid=`cat $PIDFILE`
+    grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 0
+    return 1
+  fi
+  return 3
 }
+
 
 case "$1" in
 start)
-	. /etc/profile
-
-        is_running
-        stat=$?
-        case "$stat" in
-                0) echo "Hive Thrift Server is already running..." ;;
-                1) echo "Could not access pidfile for $DESC" ;;
-                *)
-                echo "Starting "$DESC" ... "
-                [ -e `dirname "$PIDFILE"` ] || \
-                        install -d -m755 `dirname $PIDFILE`
+  . /etc/profile
+  is_running
+  stat=$?
+  case "$stat" in
+    0) echo "Hive Thrift Server is already running..." ;;
+    1) echo "Could not access pidfile for $DESC" ;;
+    *)
+      echo "Starting "$DESC" ... "
+      [ -e `dirname "$PIDFILE"` ] || \
+        install -d -m755 `dirname $PIDFILE`
 		
-		if [ "x$HIVE_HOME" = "x" ];
-		then
-        		HIVE_HOME=/opt/hive
-		fi
-        	DAEMON="$HIVE_HOME/bin/hive"
-        	ARGS=" --service hiveserver"
-                start-stop-daemon --start --make-pidfile --background --pidfile  "$PIDFILE" --exec "${DAEMON}" -- ${ARGS}
-        ;;
-        esac
+      if [ "x$HIVE_HOME" = "x" ];then
+        HIVE_HOME=/opt/hive
+      fi
+      DAEMON="$HIVE_HOME/bin/hive"
+      ARGS=" --service hiveserver"
+      start-stop-daemon --start --make-pidfile --background --pidfile  "$PIDFILE" --exec "${DAEMON}" -- ${ARGS}
+      ;;
+  esac
 ;;
-
 stop)
-        is_running
-        stat=$?
-        case "$stat" in
-        0)
-                echo "Stopping" $DESC
-                echo "PID: " $PIDFILE
-                start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
-                rm -f "$PIDFILE";;
-        1) echo "Could not access pidfile for $DESC" ;;
-        *) echo $DESC" is not running..." ;;
-        esac
+  is_running
+  stat=$?
+  case "$stat" in
+    0)
+      echo "Stopping" $DESC
+      echo "PID: " $PIDFILE
+      start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
+      rm -f "$PIDFILE";;
+    1) echo "Could not access pidfile for $DESC" ;;
+    *) echo $DESC" is not running..." ;;
+  esac
 ;;
-
 restart)
-        $0 stop
-        $0 start
+  $0 stop
+  $0 start
 ;;
-
 status)
-        is_running
-        stat=$?
-        case "$stat" in
-                0) log_success_msg "$DESC is running" ;;
-                1) log_failure_msg "could not access pidfile for $DESC" ;;
-                *) log_success_msg "$DESC is not running" ;;
-        esac
-        exit "$stat"
+  is_running
+  stat=$?
+  case "$stat" in
+    0)
+      PID=`cat $PIDFILE`
+      log_success_msg "$DESC is running(PID:$PID)" ;;
+    1) log_failure_msg "could not access pidfile for $DESC" ;;
+    *) log_success_msg "$DESC is not running" ;;
+  esac
+  exit "$stat"
 ;;
 kill)
-	start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
-	rm -f "$PIDFILE"
-	echo $DESC "is killed..."
+  start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
+  rm -f "$PIDFILE"
+  echo $DESC "is killed..."
 ;;
 *)
-        echo "Usage: $0 {start|stop|restart|status|kill}"
-        exit 1
+  echo "Usage: $0 {start|stop|restart|status|kill}"
+  exit 1
 esac
