SUBUTAI-1189: is_dpkg_locked method implemented

diff --git a/cli/src/main/bindings/destroy b/cli/src/main/bindings/destroy
--- a/cli/src/main/bindings/destroy
+++ b/cli/src/main/bindings/destroy
@@ -95,7 +95,13 @@ function destroy {
   # (3) Remove the debian package if installed
   local container=$clone
   local package_name=`get_package_name $container`
-  
+ 
+  if [ "`is_dpkg_locked`" == "true" ]
+  then
+    echo "$1 import FAILED! dpkg is locked by process!"
+    exit 1
+  fi
+ 
   # Check if the package is installed
   is_package_installed $package_name
   if [ $? = 0  ]; then
diff --git a/cli/src/main/bindings/import b/cli/src/main/bindings/import
--- a/cli/src/main/bindings/import
+++ b/cli/src/main/bindings/import
@@ -76,6 +76,12 @@ function import {
       msg_error "Template $container seems already installed, please destroy first"
       exit 1
     fi
+    
+    if [ "`is_dpkg_locked`" == "true" ]
+    then
+       echo "$1 import FAILED! dpkg is locked by process!"
+       exit 1
+    fi
 
     if [ "$is_local" == "true" ]
     then
