SUBUTAI-1995: Handle disk usage of each dataset separately

diff --git a/cli/src/main/lib/zfs_ops b/cli/src/main/lib/zfs_ops
--- a/cli/src/main/lib/zfs_ops
+++ b/cli/src/main/lib/zfs_ops
@@ -404,6 +404,7 @@ function fs_get_quota {
   printf "Container rootfs:\t%s\n" $lxc_rootfs
 }
 
+
 function fs_set_quota {
   local container=$1
   local directory=$2
@@ -433,6 +434,77 @@ function fs_set_quota {
     exit 1;
   fi
   fs_quota_operations $container $quota_value
+}
+
+
+function fs_get_disk_info {
+  local container=$1
+  local dataset=$2
+  local disk_parameter=$3
+
+  case $dataset in
+    "home")
+      dataset_name="lxc-data/$container-home";
+      ;;
+    "var")
+      dataset_name="lxc-data/$container-var";
+      ;;
+    "opt")
+      dataset_name="lxc/$container-opt";
+      ;;
+    "rootfs")
+      dataset_name="lxc/$container";
+      ;;
+    \?)
+      echo "Unsupported dataset $dataset! Aborting..";
+      exit 1;
+      ;;
+  esac
+  zfs get -p $disk_parameter $dataset_name | grep "$disk_parameter" | awk '{ print $3 }'
+}
+
+
+function fs_get_available_disk {
+  local container=$1
+  local dataset=$2
+  fs_get_disk_info $container $dataset "available"
+}
+
+
+function fs_get_used_disk {
+  local container=$1
+  local dataset=$2
+  fs_get_disk_info $container $dataset "used"
+}
+
+
+function fs_get_mount_point {
+  local dataset=$1
+  zfs get mountpoint $dataset | grep $dataset | awk '{ print $3 }'
+}
+
+
+# Returns total disk size of the resource host
+# by pool name in bytes
+function fs_get_physical_total_disk {
+  local pool=$1
+  zpool get -p size $pool | grep "$pool" | awk '{ print $3 }'
+}
+
+
+# Returns available disk size of the resource host
+# by pool name in bytes
+function fs_get_physical_available_disk {
+  local pool=$1
+  zfs get -p available $pool | grep "$pool" | awk '{ print $3 }'
+}
+
+
+# Returns used disk size of the resource host
+# by pool name in bytes
+function fs_get_physical_used_disk {
+  local pool=$1
+  zfs get -p used $pool | grep "$pool" | awk '{ print $3 }'
 }
 
 function fs_quota_operations {
